"""
schemas/__init__.py
───────────────────
すべてのスキーマモデルの公開インターフェース。

Usage:
    from schemas import FontGenerateRequest, ProjectResponse
"""

# font_schema.py からのインポート
from .font_schema import (
    FontMetricsInput,
    FontMetricsResponse,
    ContourPointInput,
    ContourInput,
    GlyphMetricsInput,
    GlyphDataInput,
    GlyphDataResponse,
    FontMetadataInput,
    FontMetadataResponse,
    FontGenerateRequest,
    FontResponse,
    FontListResponse,
    FontSubsetRequest,
    FontConvertRequest,
    FontVariableAdjustRequest,
    FontSubsetResponse,
    FontConvertResponse,
    FontPreviewRequest,
    FontPreviewResponse,
    FontExportRequest,
    FontExportResponse,
    StrokeSettingsInput,
    StrokeSettingsResponse,
    FontWithStrokeRequest,
    FontGenerationHistoryEntry,
    FontGenerationHistoryListResponse,
    FontCacheInfo,
    ErrorResponse as FontErrorResponse,
    ValidationErrorResponse as FontValidationErrorResponse,
)

# project_schema.py からのインポート
from .project_schema import (
    ProjectStatus,
    ProjectCreateRequest,
    ProjectUpdateRequest,
    ProjectSettingsResponse,
    ProjectStatistics,
    ProjectResponse,
    ProjectListResponse,
    ProjectDetailResponse,
)

# export_schema.py からのインポート
from .export_schema import (
    ExportFormat,
    ExportPackageFormat,
    FontExportOptions,
    HTMLExportOptions,
    ZipExportOptions,
    ExportRequest,
    ProjectExportRequest,
    ExportResponse,
    BulkExportResponse,
    ExportStatusResponse,
    ExportHistoryEntry,
    ExportHistoryResponse,
    ExportStatistics,
)

# llm_schema.py からのインポート
from .llm_schema import (
    MessageRole,
    ChatMessage,
    ChatHistoryEntry,
    ChatRequest,
    ChatStreamRequest,
    ChatResponse,
    ChatStreamResponse,
    DesignInstruction,
    DesignInstructionParsedResponse,
    PromptContext,
    PromptBuilderRequest,
    SessionCreateRequest,
    SessionResponse,
    LLMProviderConfig,
    LLMProvidersResponse,
)

# common_schema.py からのインポート
from .common_schema import (
    ErrorResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
    PaginationRequest,
    PaginationMeta,
    PaginatedResponse,
    ServiceStatus,
    StatusResponse,
    DatabaseHealthResponse,
    PythonBackendHealthResponse,
    HealthCheckResponse,
    FilterOperator,
    SearchFilter,
    SearchRequest,
    BatchRequest,
    BatchOperationResult,
    BatchResponse,
    AsyncOperationStatus,
    AsyncOperationRequest,
    AsyncOperationResponse,
    AuditAction,
    AuditLogEntry,
    AuditLogResponse,
    WebhookEventType,
    WebhookEvent,
    SubscriptionResponse,
)

__all__ = [
    # Font schemas
    "FontMetricsInput",
    "FontMetricsResponse",
    "ContourPointInput",
    "ContourInput",
    "GlyphMetricsInput",
    "GlyphDataInput",
    "GlyphDataResponse",
    "FontMetadataInput",
    "FontMetadataResponse",
    "FontGenerateRequest",
    "FontResponse",
    "FontListResponse",
    "FontSubsetRequest",
    "FontConvertRequest",
    "FontVariableAdjustRequest",
    "FontSubsetResponse",
    "FontConvertResponse",
    "FontPreviewRequest",
    "FontPreviewResponse",
    "FontExportRequest",
    "FontExportResponse",
    "StrokeSettingsInput",
    "StrokeSettingsResponse",
    "FontWithStrokeRequest",
    "FontGenerationHistoryEntry",
    "FontGenerationHistoryListResponse",
    "FontCacheInfo",
    "FontErrorResponse",
    "FontValidationErrorResponse",
    # Project schemas
    "ProjectStatus",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectSettingsResponse",
    "ProjectStatistics",
    "ProjectResponse",
    "ProjectListResponse",
    "ProjectDetailResponse",
    # Export schemas
    "ExportFormat",
    "ExportPackageFormat",
    "FontExportOptions",
    "HTMLExportOptions",
    "ZipExportOptions",
    "ExportRequest",
    "ProjectExportRequest",
    "ExportResponse",
    "BulkExportResponse",
    "ExportStatusResponse",
    "ExportHistoryEntry",
    "ExportHistoryResponse",
    "ExportStatistics",
    # LLM schemas
    "MessageRole",
    "ChatMessage",
    "ChatHistoryEntry",
    "ChatRequest",
    "ChatStreamRequest",
    "ChatResponse",
    "ChatStreamResponse",
    "DesignInstruction",
    "DesignInstructionParsedResponse",
    "PromptContext",
    "PromptBuilderRequest",
    "SessionCreateRequest",
    "SessionResponse",
    "LLMProviderConfig",
    "LLMProvidersResponse",
    # Common schemas
    "ErrorResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    "PaginationRequest",
    "PaginationMeta",
    "PaginatedResponse",
    "ServiceStatus",
    "StatusResponse",
    "DatabaseHealthResponse",
    "PythonBackendHealthResponse",
    "HealthCheckResponse",
    "FilterOperator",
    "SearchFilter",
    "SearchRequest",
    "BatchRequest",
    "BatchOperationResult",
    "BatchResponse",
    "AsyncOperationStatus",
    "AsyncOperationRequest",
    "AsyncOperationResponse",
    "AuditAction",
    "AuditLogEntry",
    "AuditLogResponse",
    "WebhookEventType",
    "WebhookEvent",
    "SubscriptionResponse",
]
